openapi: 3.0.0
servers:
  - description: AthletX API
    url: http://localhost:<port>/api/v1
info:
  description: This is the API of the AthletX Server
  version: 1.1.0
  title: AthletX API
  contact:
    email: info@athletx.com
  license:
    name: MIT License
    url: 'https://opensource.org/license/mit/'
