openapi: 3.0.0
servers:
  - description: AthletX Server REST-API
    url: http://localhost:<port>/api/v1
info:
  description: This is the available REST API of the AthletX Web Server
  version: 1.1.0
  title: AthletX Server REST-API
  contact:
    email: info@athletx.com
  license:
    name: MIT License
    url: 'https://opensource.org/license/mit/'

tags:
  - name: Auth API
    description: This is the available API to authenticate users.

paths:
  /signup:
    post:
      tags:
        - Auth API
      summary: User Signup
      operationId: signupUser
      description: Registrate a User
      responses:
        '201':
            description: User created
        '409':
          description: User exists
        '422':
          description: Invalid fields
  /login:
    post:
      tags:
        - Auth 
      summary: User Login
      operationId: loginUser
      description: Authenticate a User
      responses:
        '200':
            description: User logged
        '401':
          description: Invalid Credentials
        '422':
          description: Invalid fields
  /logout:
    post:
      tags:
        - Auth 
      summary: User Logout
      operationId: logoutUser
      description: Deauthenticate a User
      responses:
        '201':
            description: User logged out